name: Weekly AQI Email

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: pip install requests firebase-admin plotly kaleido
      
      - name: Create Firebase credentials file
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: echo "$FIREBASE_KEY" > firebase-key.json
      
      - name: Run AQI email script
        env:
          IQAIR_API_KEY: ${{ secrets.IQAIR_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: python3 aqi_email.py